### ISSUE TITLE
The received API response does not contain a user

### ISSUE THREAD

**Issue by agolebiowska** [knojector/SteamAuthenticationBundle#11]
Hi! First, thank you for this great bundle!
I am trying to use it with symfony4, but every time I get this 
`InvalidApiResponseException('The received API response does not contain a user.');`
and the `$data['response']['players']` is empty, even when I provide other id. I don't know what am I doing wrong. Can you tell me what 'players' means exactly?
This is my conf:
`knojector_steam_authentication:
    api_key: "%env(STEAM_API_KEY)%"
    login_route: 'home'
    login_redirect: 'home'
    user_class: 'App\Entity\User'`

**Comment by knojector** [comment]
Hi,

sorry for the late response!

Have you already found a solution for this problem? I never encountered this problem during development.
