### ISSUE TITLE
Unexpected token "punctuation" of value ":".

### ISSUE THREAD

**Issue by diriy** [knojector/SteamAuthenticationBundle#20]
I have implemented all the requirements from the READme but received the following error:

**Unexpected token "punctuation" of value ":".**

My code is totally the same like in the documentation:

```
     {% include '@KnojectorSteamAuthentication/login.html.twig' with: { 'btn': 1 } %}
```

What could be wrong?

That works without ":" after "with" and I suppose that there is a typo in READme, isn't it?

**Comment by hypefactorybrian** [comment]
Just change 
` {% include '@KnojectorSteamAuthentication/login.html.twig' with: { 'btn': 1 } %}`
to this:
`{% include '@KnojectorSteamAuthentication/login.html.twig' with { 'btn': 1 } %}`

Simple remove `:`

**Comment by knojector** [comment]
fixed with https://github.com/knojector/SteamAuthenticationBundle/pull/24
