### ISSUE TITLE
Class 'user' doesn't exist

### ISSUE THREAD

**Issue by camerpu** [knojector/SteamAuthenticationBundle#35]
Class User exist on App/Entity (class User extends AbstractSteamUser), but after logging is error:
Class 'User' doesn't exist

**    user_class: 'User'
**
on cfg

**Comment by insideone** [comment]
I suppose `user_class: App\Entity\User` will do the work

**Comment by camerpu** [comment]
Then
Class "App\Entity\User" sub class of "Knojector\SteamAuthenticationBundle\User\AbstractSteamUser" is not a valid entity or mapped super class.

**Comment by camerpu** [comment]
Ok, adding
/**
 * @author Knojector <dev@knojector.xyz>
 *
 * @ORM\Entity()
 */

Helped, thanks
