### ISSUE TITLE
Error on prod SteamUserToken::__serialize() must return an array

### ISSUE THREAD

**Issue by DorianHub** [knojector/SteamAuthenticationBundle#36]
Hi.
On local machine works fine, but on production I get this error "Knojector\SteamAuthenticationBundle\Security\Authentication\Token\SteamUserToken::__serialize() must return an array"

**Comment by insideone** [comment]
Sorry, my fault. I've just added the fix to #33

You can use my fork to have immediate use of it or wait for @knojector to accept PR

**Comment by knojector** [comment]
accepted ;)
