### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by brnicot** [knojector/SteamAuthenticationBundle#5]
Hi,
Since I can connect thanks to the https fix ; I've got few questions : 

- should the table corresponding to the users be created automatically ? it wasn't the case for me so I had to create it by myself
- what means login_route and login_redirect ? isn't it the same thing ?

thanks

**Comment by knojector** [comment]
Hi @brnicot,

you can use the doctrine:schema:create command the create a corresponding mysql table.

In some use cases the login_redirect might be different.

**Comment by brnicot** [comment]
Sorry for these dumb questions, just thought the table would be created automatically ;)
and could you explain in which cases it might be different ? is it first the login_route that is launched and then, once login done it is redirected to login_redirect ?

thanks

**Comment by knojector** [comment]
E.g a user should be redirected to his profile page after login.

The login_route is sent as request parameter to the steam api. After the login, steam redirects the user to the given login_route. As you can see in the [SteamListener.php](https://github.com/knojector/SteamAuthenticationBundle/blob/c5ca4ec4aa9bb86dcc4501221baaac17e237ce04/Security/Firewall/SteamListener.php#L74) the following code is only executed if the routes do match. So the user is never really redirected to the login_route from your applications point of view. Only from the steam api. 
The login_redirect is the route the user is redirected to from your application if the user could  be authenticated.
