### ISSUE TITLE
Question about roles

### ISSUE THREAD

**Issue by GrosTon1** [knojector/SteamAuthenticationBundle#6]
Hello,

Im strugling for about 4 hours with roles and cant manage to do anything with them, so two simple questions :

- How can I make everyone have "ROLE_USER" for example.
- How can I give myself a custom role like "ROLE_OWNER".

Maybe not related to the bundle, but I cant find anything on google.

Cheers.

**Comment by knojector** [comment]
Hi,

Roles are just Strings. In the constructor in the documentation of this bundle you can set the roles to ['ROLE_USER'] instead of []. 
You can write your own functions to change the roles array.

**Comment by knojector** [comment]
There is a detailed explanation about the Role-Usage in the [Symfony Docs](https://symfony.com/doc/current/security.html#denying-access-roles-and-other-authorization)

**Comment by GrosTon1** [comment]
Despite the fact I've read this multiple times, I can't get roles to work with your bundle.
It works in the database (the created users have the role) but it still pops the error while returning from steam.
Are you sure it's not an issue with your bundle ?

**Comment by GrosTon1** [comment]
So, I tried these things :
```php
public function __construct()
{
    $this->roles = ['ROLE_SOMETHING'];
}
```
Throws FatalThrowableError -> Call to a member function getRole() on string, but the "roles" column in my database now contains ["ROLE_SOMETHING"]
```php
public function getRoles()
{
    return ['ROLE_SOMETHING'];
}
```
Throws FatalThrowableError -> Call to a member function getRole() on string
Tried to just modify the column value and add "ROLE_SOMETHING" to the array for my user row, same error.

Don't know if this can help, but I'm using MySQL CE 5.7.2, and I suspect that it's because of the type mapping with the roles property.

**Comment by knojector** [comment]
Do you use the `isGranted()` method of the `AuthorizationCheckerInterface`?

Since you use the RoleHierarchy the you need the implement a getRoles method that return a [Role](https://api.symfony.com/master/Symfony/Component/Security/Core/Role/Role.html)

Does this code work?
`at RoleHierarchy->getReachableRoles(array(new Role('ROLE_USER')))in SecurityDataCollector.php line 104`

**Comment by GrosTon1** [comment]
So,
```php
public function getRoles()
{
    return [new Role('ROLE_USER')];
}
```
Works as planned, but
```php
public function __construct()
{
    $this->roles = [new Role('ROLE_USER')];
}
```
does not (forgot to mention that I tried that one) and throws FatalThrowableError -> Call to a member function getRole() on array (still with the stack "in RoleHierarchy.php line 41").

About your question, I don't, I'm only passing the UserInterface to my twig template

**Comment by knojector** [comment]
In your Twig template you can use the function `is_granted('ROLE_USER')` to check if the user has the required role.

Or you override the getRoles() method in your User Entitiy so that an array of Role Objects is returned:

```php
public function getRoles(): array {
    $roles = [];
    foreach ($this->roles as $role) {
        $roles[] = new Role($role);
    }
}

return $roles;
```

**Comment by GrosTon1** [comment]
Yes, I know how to check if users have roles or not, the problem is that I can't store roles in my Database (because I can't either use my User's contrustor or add it directly in db), and my project need multiples roles for administration thing and stuff...
The return is outside the bracket instead of being inside by the way, and thank's for trying to help.

**Comment by knojector** [comment]
`FatalThrowableError
Call to a member function getRole() on string`
With your current `getRoles()` method an array of Role strings is returned.

In your custom `getRoles()` method you should [transform](https://github.com/knojector/SteamAuthenticationBundle/issues/6#issuecomment-388579737) each Role string into an Role object.


The Role Object is never persisted to the database. In the database column there should only be an array of Role strings. 

Have you tried to replace your `getRoles()` method with mine?

**Comment by knojector** [comment]
I'm glad that it's working :)

Feel free to create a PR :)
