### ISSUE TITLE
Symfony v6 Compatibility 

### ISSUE THREAD

**Issue by NathanBaker2000** [knojector/SteamAuthenticationBundle#7]
Hi,

Do you plan in adding compatibility with Symfony v6?

Or do you know whether this works with Symfony V6

Thanks,
Nathan

**Comment by knojector** [comment]
Hi @NathanBaker2000,

I created a new version [(1.3.0)](https://github.com/knojector/SteamAuthenticationBundle/releases/tag/1.3.0) that is compatible with Symfony 6. You should update your composer.json to ^1.3 and run composer update.
